### ISSUE TITLE
Add more components

### ISSUE THREAD

**Issue by bojidar917** [bojidar917/exam_task_2021#1]
`inline Configuration *createConfiguration()
{
   try
   {
        // static Configuration* configuration = new Configuration(); //why do we need it to be static - svilen said so
        Configuration* configuration = new Configuration(); 
        
        const Component* component = componentFactory();
        configuration->insert(component);

        const Component* othercomponent = componentFactory();
        configuration->insert(othercomponent);

        // std::cout << configuration;

        return configuration;
   }
   catch(...)
   {
        return nullptr;
   }
    //в мейна трябва да се погрижим да се зачисти паметта
}`

How to add more than two components? Should I pass ostream and have a while loop to read multiple times?

**Comment by svilenbs** [comment]
static is required in case we want to make sure that for sure we will generate only one instance of Configuration.

Regarding the second question - other possible solutions are type method / byte operations such as flags.

**Comment by dimbata23** [comment]
I don't agree with @svilenbs for the static. This function is named **CREATE**configuration, it should create a new configuration each time it's called (just like you've written). static will only create one configuration (and if you call the function more than once it'll just add components to that SINGLE configuration it has already created, instead of giving you a new configuration)


Edit: Oops, I didn’t fully read @svilenbs’s answer. Yes, static is required in case you want ONLY one instance of the class to be created. But then the insert of components should be handled such that they’re only inserted once.

**Comment by dimbata23** [comment]
As for adding more components - yes, you can definitely just use std::cin in a while loop and ask if the person wants to add any more components until they say "no".
